language: generic 
services:
  - docker
cache:
  directories:
    - $HOME/.ccache
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros AFTER_SETUP_TARGET_WORKSPACE='./scripts/ci_prebuild.sh' AFTER_SCRIPT='./scripts/ci_postbuild.sh'
    - ROS_DISTRO="noetic" ROS_REPO=ros AFTER_SETUP_TARGET_WORKSPACE='./scripts/ci_prebuild.sh'
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

script: 
  - .industrial_ci/travis.sh
